- charts/datarepo-api/Chart.yaml
- charts/datarepo-api/templates/api-deployment.yaml
- charts/datarepo-api/values.yaml
- charts/datarepo-ui/Chart.yaml
- charts/datarepo-ui/templates/ui-deployment.yaml
- charts/datarepo-ui/values.yaml
- charts/oidc-proxy/Chart.yaml
- charts/oidc-proxy/templates/oidc-proxy-deployment.yaml
- charts/oidc-proxy/values.yaml
This makes it so the chart will not need to be updated when a new application environment variable is created and pod annotations can be added dynamically.
example api config:
```
env:
GOOGLE_PROJECTID:  broad-jade-integration
DB_DATAREPO_USERNAME:  drmanager
SPRING_PROFILES_ACTIVE:  google,cloudsql,temp
DB_STAIRWAY_USERNAME:  drmanager
DB_STAIRWAY_URI: jdbc:postgresql://chart-test-gcloud-sqlproxy.temp:5432/stairway-temp
DB_DATAREPO_URI: jdbc:postgresql://chart-test-gcloud-sqlproxy.temp:5432/datarepo-temp
IT_JADE_API_URL: https://jade-temp.datarepo-integration.broadinstitute.org
DATAREPO_GCS_ALLOWREUSEEXISTINGBUCKETS: true
```
> MS Added dynamic env vars and annotations

- .github/workflows/lint.yaml
The latest version of the GitHub action cleans the IAM policy before it is run:
- https://github.com/broadinstitute/datarepo-actions/pull/8
- https://github.com/broadinstitute/datarepo-actions/pull/9
The action version was automatically bumped and released: https://github.com/broadinstitute/datarepo-actions/releases/tag/0.6.0
> DR-977: Bump action version to 0.6.0

- charts/install-secrets-manager/Chart.yaml
- charts/install-secrets-manager/templates/deployment.yaml
As per https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
> Deployment in the extensions/v1beta1, apps/v1beta1, and apps/v1beta2 API versions is no longer served
> Migrate to use the apps/v1 API version, available since v1.9. Existing persisted data can be retrieved/updated via the new version.
> Update deployment API to work for 1.16

- charts/datarepo-api/Chart.yaml
- charts/datarepo-api/templates/api-deployment.yaml
- charts/gcloud-sqlproxy/Chart.yaml
- charts/gcloud-sqlproxy/templates/deployment.yaml
- charts/oidc-proxy/Chart.yaml
- charts/oidc-proxy/templates/oidc-ingress.yaml
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
After this weekend fixing fakeprod, I had to modify the charts for the kubernetes 1.16 API depreciation.
> bumped charts for gke 1.16

- charts/datarepo-api/Chart.yaml
- charts/datarepo-api/templates/api-deployment.yaml
Our startup time continues to get longer and longer. It is a combination of additional liquidate migrations as well as more synchronization with stairway. I made the probe time significantly longer.
> Extend probe timeouts

- charts/oidc-proxy/Chart.yaml
- charts/oidc-proxy/templates/oidc-proxy-deployment.yaml
- charts/oidc-proxy/values.yaml
env vars are as followed 
```    
ENABLE_TCELL: yes
TCELL_LOG_DIR: /var/log
```
Then the config is mounted as a secret via secret manager to the tcell config path
secret manger secret path 
```
- secretName: tcellconfig
vals:
- kubeSecretKey: tcellconfigkey
path: secret/dsde/datarepo/production/tcellconfig
encoding: base64
vaultKey: key
``` 
Prod config here https://github.com/broadinstitute/terra-helmfile/pull/149/files
> Adding tcell functionality

- charts/datarepo-ui/Chart.yaml
- charts/datarepo-ui/templates/configmap.yaml
- charts/datarepo-ui/templates/ui-deployment.yaml
- charts/datarepo-ui/values.yaml
PR does a couple of things:
- Fix the helm chart so that only the nginx.conf file is overlaid in /etc/nginx so the entire directory doesn't get squashed
- Bump the version of the UI image
- Update the default UI docker image
> Configure MIME types for CSS

- charts/oidc-proxy/Chart.yaml
- charts/oidc-proxy/templates/configmap.yaml
This allows any origin but locks down which headers and methods will be passed through
> DR-1529 Enable CORS headers on requests served by the oidc proxy

- charts/oidc-proxy/Chart.yaml
- charts/oidc-proxy/templates/configmap.yaml
Since many terra apps use this.  This is a follow-on to my last PR where it looks like we need this based on WMS testing this out. Removing this header from their requests makes things work but looking at services like SAM, they allow this header so we probably should too.
Will do the chart updates as soon as this one is merged in...
> DR-1529 Allow the x-app-id and origin headers to be passed in

- charts/datarepo-api/Chart.yaml
Update datarepo-api versions in **1.18.0**.
*Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/DataBiosphere/jade-data-repo/actions/runs/575490207).*
> Datarepo version update: 1.18.0

- charts/datarepo-api/Chart.yaml
- charts/datarepo-api/values.yaml
Update datarepo-api versions in **1.21.0**.
*Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/DataBiosphere/jade-data-repo/actions/runs/578807767).*
> Datarepo datarepo-api version update: 1.21.0

- charts/datarepo-api/Chart.yaml
- charts/datarepo-api/values.yaml
Update datarepo-api versions in **1.22.0**.
*Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/DataBiosphere/jade-data-repo/actions/runs/582445523).*
> Datarepo datarepo-api version update: 1.22.0

- charts/datarepo-api/Chart.yaml
- charts/datarepo-api/values.yaml
Update datarepo-api versions in **1.24.0**.
*Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/DataBiosphere/jade-data-repo/actions/runs/582666729).*
> Datarepo datarepo-api version update: 1.24.0

- charts/datarepo-api/Chart.yaml
- charts/datarepo-api/values.yaml
Update datarepo-api versions in **1.25.0**.
*Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/DataBiosphere/jade-data-repo/actions/runs/582813479).*
> Datarepo datarepo-api version update: 1.25.0

- charts/datarepo-api/Chart.yaml
- charts/datarepo-api/values.yaml
Update datarepo-api versions in **1.26.0**.
*Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/DataBiosphere/jade-data-repo/actions/runs/587310064).*
> Datarepo datarepo-api version update: 1.26.0

- charts/datarepo-api/Chart.yaml
- charts/datarepo-api/values.yaml
Update datarepo-api versions in **1.27.0**.
*Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/DataBiosphere/jade-data-repo/actions/runs/589830141).*
> Datarepo datarepo-api version update: 1.27.0

- charts/datarepo-api/Chart.yaml
- charts/datarepo-api/values.yaml
Update datarepo-api versions in **1.28.0**.
*Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/DataBiosphere/jade-data-repo/actions/runs/590902837).*
> Datarepo datarepo-api version update: 1.28.0

- charts/datarepo-api/Chart.yaml
- charts/datarepo-api/values.yaml
Update datarepo-api versions in **1.29.0**.
*Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/DataBiosphere/jade-data-repo/actions/runs/592782139).*
> Datarepo datarepo-api version update: 1.29.0

- charts/datarepo-api/Chart.yaml
- charts/datarepo-api/values.yaml
Update datarepo-api versions in **1.30.0**.
*Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/DataBiosphere/jade-data-repo/actions/runs/594720487).*
> Datarepo datarepo-api version update: 1.30.0

- charts/datarepo-api/Chart.yaml
- charts/datarepo-api/values.yaml
Update datarepo-api versions in **1.31.0**.
*Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/DataBiosphere/jade-data-repo/actions/runs/594765260).*
> Datarepo datarepo-api version update: 1.31.0

- charts/datarepo-api/values.yaml
This will make it a bit easier for k8s to schedule a pod
> DR-1642 Lower the amount of memory requested to schedule a pod

- charts/oidc-proxy/Chart.yaml
- charts/oidc-proxy/ci/testing-values.yaml
- charts/oidc-proxy/templates/configmap.yaml
Include the ga4gh endpoint in the oidc-proxy configmap. Note the [broadinstitute/openidc-proxy](https://github.com/broadinstitute/openidc-proxy#openidc-proxy) image used by the chart sets default values for some environment variables, so they are not all specified in the values.yaml.
I tested this change in my personal developer data repo deployment: https://github.com/broadinstitute/datarepo-helm-definitions/pull/387
> [DR-1658] Add /ga4gh path to oidc-proxy

- .github/workflows/test.yaml
- charts/datarepo-ui/templates/configmap.yaml
Setting `server_tokens` to `off` removes the version from the `server` response header header,.
> DR-1650 remove nginx server tokens

- charts/datarepo-ui/templates/configmap.yaml
We need to add [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/Introducing_Content_Security_Policy) headers to our UI nginx server to satisfy security requirements. We currently don't have the code set up to do nonces, so `unsafe-inline` has to be used in several places. I tested this in my personal deployment and kept adding domains until there were no errors when the page loaded.
> DR-1651 Content-Security-Policy headers

- charts/oidc-proxy/Chart.yaml
- charts/oidc-proxy/templates/configmap.yaml
This fixes an issue where the `Access-Control-Allow-Origin` wasn't getting set on `OPTIONS` requests.  Makes this `always`, the way it is for other CORS headers
> DR-1652 Make sure that the Access-Control-Allow-Origin response header is always set

- charts/datarepo-ui/Chart.yaml
- charts/datarepo-ui/templates/configmap.yaml
Missed one! We need this domain in the `script-src` section of the CSP headers for prod. It didn't show up in any other environment, and doesn't appear to break anything, but its good to not have errors in the console. Thanks to @nmalfroy for spotting this!
> DR-1769 Add jsagent.tcell.io to script-src

- charts/sqlbackup/Chart.yaml
- charts/sqlbackup/templates/_helpers.tpl
- charts/sqlbackup/values.yaml
AppSec currently gets nightly alerts about our psql backup because we install `jq` at runtime. By using `broadinstitute/dsde-toolbox`, we can remove the install of `jq` without needing to host our own image. The image is a little bigger (~1.5GB), but given that its only ever localized upon deploy, I don't think it's too big of a deal, especially since the compressed size is only ~350MB, which is what would get transferred over the network.
We need to specify full paths to `gcloud` within the scripts since `dsde-toolbox` doesn't add the Google Cloud SDK binaries to the `PATH`. I rendered the chart locally, and manually ran the list-backups command within a local `dsde-toolbox` container, and it spit out all the backups as expected. I'm unsure of how we would test this in kubernetes, since …
> DR-1771 dont install jq at runtime psql backup

- charts/datarepo-ui/Chart.yaml
- charts/datarepo-ui/templates/ui-deployment.yaml
We're removing the readiness and liveliness probes from the UI server so that it stays up even when the API is down or returns a non-200 response. The UI will handle the error messaging to the user.
> DR-1665 keep UI up when server down

- charts/datarepo/Chart.yaml
I think we introduced a conflict when we manually edited the umbrella chart without bumping it
> DR-1822 Manually bump the umbrella chart

- charts/gcloud-sqlproxy/templates/deployment.yaml
https://broadinstitute.slack.com/archives/CADM7MZ35/p1639406743425800
`kubectl` rollout commands run against the gcloud sqlproxy deployment cause ArgoCD to think TDR is out of sync.
This seems to be because the deployment manifest sets annotations to `{}`, which makes ArgoCD think the resource should have NO annotations. Unfortunately syncing does not remove the extraneous annotations. It just means that ArgoCD goes out of sync immediately after a sync is triggerd.
This causes Terra's deploy process to fail, because it waits for ArgoCD apps to become healthy after syncing.
> DDO-1814 Fix issue where `kubectl rollout` breaks ArgoCD syncs for TDR

- charts/de-elasticsearch/values.yaml
I ran the following Dockerfile:
```
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
RUN yum -y update \
&& cd /usr/share/elasticsearch/lib \
&& curl -O https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar \
&& curl -O https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar \
&& rm log4j-*-2.11.1.jar
```
It updates the base software in CentOS, updates the elasticsearch log4j jars, and removes the old jars.
> Switch Elasticsearch OSS image to patched version

- charts/de-elasticsearch/Chart.yaml
- charts/de-elasticsearch/values.yaml
This is a two part PR. In the first PR, I update the elasticsearch container and the helm chart. In the second PR, I update the datarepo umbrella helm chart.
The Dockerfile that generated the container:
```
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
RUN yum -y update \
&& cd /usr/share/elasticsearch/lib \
&& curl -O https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar \
&& curl -O https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar \
&& rm log4j-*-2.11.1.jar
```
> DC-97: Update elasticsearch-oss with latest log4j

- charts/datarepo/ci/testing-values.yaml
Now that the chart is merged without the shutdown value, we don't need to pass it in to the chart test
> DR-2331 Remove shutdown test value

- .github/workflows/releasedr.yaml
There appears to be some race condition that causes the action after the pause to fail pretty regularly.  Seeing if adding a pause here helps
> DR-2346 Pause before running the umbrella release action

- charts/oidc-proxy/Chart.yaml
- charts/oidc-proxy/templates/configmap.yaml
...which a) is better b) has the benefit of shrinking the data of what gets cached to fix the issue where tokens returned by google grew in size due to padding
> PROD-634 Use an encrypted cache

- charts/oidc-proxy/Chart.yaml
- charts/oidc-proxy/templates/configmap.yaml
Same fix as https://github.com/broadinstitute/firecloud-develop/pull/2802.
Updates Terra Data Repo.
> [PROD-634] Use GET instead of POST for the OAuth2 introspection endpoint

- charts/oidc-proxy/templates/configmap.yaml
Simple pass through which, along with https://github.com/DataBiosphere/jade-data-repo-ui/pull/1082 will get rid of the CORS exceptions we've been seeing
Worth noting that this does NOT authenticate the requests.  It assumes that BQ will authorize the request
> DR-2457 Proxy BigQuery requests from the apache proxy

- charts/datarepo-api/Chart.yaml
- charts/datarepo-api/templates/deployReport.yaml
- charts/datarepo-api/values.yaml
- charts/datarepo-ui/Chart.yaml
- charts/datarepo-ui/templates/deployReport.yaml
- charts/datarepo-ui/values.yaml
This PR adds support for adding accelerate metrics reporting to `datarepo-api` and `datarepo-ui`. I handled them separately because from what I could telll they are independently versioned and released.  Long story short this means that `datarepo-api` and `datarepo-ui` will show up on [this dashboard](https://grafana.dsp-devops.broadinstitute.org/d/hUZ3X92nk/terra?orgId=1). 
If I'm understanding the workflow in this repo correctly, once this is merged I then need to version bump the `datarepo-api` and `datarepo-ui` dependencies in the `datarepo` umbrella chart in a separate PR?
This PR is leveraging a [helm library chart](https://helm.sh/docs/topics/library_charts). These are yaml template definitions which are usable across multiple different helm charts. `deployReport.yaml` is the …
> DDO-1674 Accelerate Metric Reporting for Data Repo

- charts/datarepo-api/Chart.yaml
- charts/datarepo-ui/Chart.lock
- charts/datarepo-ui/Chart.yaml
The pod security policies in the data-repo chart are more restrictive than those in the rest of terra. Updatiing the metrics reporter to account for this.
> DDO-1674 Account for more restrictive Pod Security Policies

- .github/workflows/test.yaml
- charts/datarepo-ui/Chart.yaml
- charts/datarepo-ui/templates/configmap.yaml
otherwise react explodes, complaining that the domain is not trusted and TDR fails to complete loading.
This is required for BEEs as we will be using *.envs-terra.bio as a domain.
disclaimer: Not sure what the policy here is for merging, so I'm just creating this PR and pinging people for now.
> DD-1918 added new *.envs-terra.bio to allowed domains for csp

- charts/datarepo-ui/Chart.yaml
- charts/datarepo-ui/templates/configmap.yaml
- charts/oidc-proxy/Chart.yaml
- charts/oidc-proxy/templates/configmap.yaml
- charts/oidc-proxy/templates/oidc-proxy-deployment.yaml
- charts/oidc-proxy/values.yaml
This PR does the following:
- Pulls in the new Apache proxy that we should be using now to allow talking to B2C
- Allows poking through the /oauth2 path to support auth hosted by TDR
> DR-2504 OIDC config support

- charts/datarepo-api/Chart.yaml
- charts/datarepo-api/templates/_helpers.tpl
- charts/datarepo-api/templates/api-deployment.yaml
- charts/datarepo-api/values.yaml
This simply adds an optional set of values that allows a deployment to specify an oauth client secret
I've deployed and tested manually both with and without the secret in my personal deployment to confirm that it works
> DR-2504 Add support for defining an oauth client secret

- charts/datarepo-ui/Chart.yaml
Looks like the version got bumped between when I opened and merged the PR.  Manually bumping to take the OIDC changes into account
> DR-2504 Manually bump the version of the UI chart

- charts/datarepo-ui/Chart.yaml
- charts/datarepo-ui/templates/configmap.yaml
- charts/oidc-proxy/Chart.yaml
- charts/oidc-proxy/templates/configmap.yaml
- charts/oidc-proxy/templates/oidc-proxy-deployment.yaml
- charts/oidc-proxy/values.yaml
We recently updated the apache proxy image and with that came a new version of the TCell agent.  This fix makes it so that we should be able to launch with TCell enabled with the next monolith release.
TLDR: this changes the format of the config JSON and pulls down the TCell API key into from a secret now (rather than the whole config)
I also fixed the UI proxy so that the javascript agent gets loaded too
> DR-2562 Fix TCell config for prod

- charts/oidc-proxy/Chart.yaml
- charts/oidc-proxy/templates/configmap.yaml
https://broadworkbench.atlassian.net/browse/DR-2583
**Objectives**
Allow select ga4gh endpoints to be accessible without authorization.
- [GetServiceInfo](https://jade-ok.datarepo-dev.broadinstitute.org/swagger-ui.html#/DataRepositoryService/GetServiceInfo)
- [OptionsObject](https://jade-ok.datarepo-dev.broadinstitute.org/swagger-ui.html#/DataRepositoryService/OptionsObject)
- [PostObject](https://jade-ok.datarepo-dev.broadinstitute.org/swagger-ui.html#/DataRepositoryService/PostObject)
- [PostAccessUrl](https://jade-ok.datarepo-dev.broadinstitute.org/swagger-ui.html#/DataRepositoryService/PostAccessUrl)
Requirements for accessing all other endpoints should remain unchanged.
**Verification**
These configurations have been deployed to my dev environment: …
> [DR-2583] Allow select ga4gh endpoints to be unauthed

- charts/datarepo/Chart.lock
- charts/datarepo/Chart.yaml
- charts/datarepo/values.yaml
- charts/oidc-proxy/values.yaml
1) adds a dependency chart `postgres` from `terra-helmfile` for BEEs to be able to have postgres-in-k8s
2) removes the `postgresql` helm chart value, as it looks unused
3) added new `postgres` helm chart value to stay consistent with other places. Also did not want to have two similarly named variables.
Also, got a linting error trying to update values, looks like a false positive but dunno.
```{22-04-11 15:03}wm365-d96:~/codes/datarepo-helm@DDO-2017-local-postgres-for-BEEs✗✗✗✗✗✗ juyang% git commit -m "changes values instances of 'postgresql' to 'postgres' as far as I can tell that's an unused flag, also, chart bump"
charts/datarepo/values.yaml:24:  ##  "type": "service_account"
charts/datarepo/values.yaml:73:  ##  "type": "service_account"
[ERROR] Matched one or more prohibited patterns …
```
> Ddo 2017 local postgres for bees

- charts/datarepo-api/templates/_helpers.tpl
- charts/datarepo-api/templates/pod-running-policy.yaml
- charts/datarepo-api/templates/role.yaml
- charts/datarepo-api/values.yaml
- charts/datarepo-ui/templates/_helpers.tpl
- charts/datarepo-ui/templates/pod-running-policy.yaml
- charts/datarepo-ui/templates/role.yaml
- charts/datarepo-ui/values.yaml
- charts/oidc-proxy/templates/_helpers.tpl
- charts/oidc-proxy/templates/pod-running-policy.yaml
- charts/oidc-proxy/templates/role.yaml
- charts/oidc-proxy/values.yaml
We're running into cross-namespace conflicts with TDR's PodSecurityPolicies in BEEs:
This is because unlike other types of K8s resources, PSPs are cluster-level and not scoped to a namespace. Every BEE is sharing (and attempting to manage) the same PSP object.
This PR addresses the issue by adding a new Helm chart value, `rbac.namespacePrefix`, to the `datarepo-api`, `datarepo-ui`, and `oidc-proxy` Helm charts. When set to `true`, the names of the PSPs in these charts will be prefixed with the release's namespace. This new value defaults to `false` and will only be enabled in BEEs.
> DDO-2153 Prefix PSPs with namespace in BEEs

- charts/install-secrets-manager/Chart.yaml
- charts/install-secrets-manager/templates/role.yaml
- charts/install-secrets-manager/values.yaml
I'm trying to run secrets manager on an aks cluster. PSPs are deprecated in AKS but this chart couples psps to other rbac resources like clusterRoles etc which are needed. This PR aims to decouple  them in a backwards compatible manner
> DDO-2562 Support Secrets Manager in AKS - Decouple RBAC and PSP

- charts/install-secrets-manager/Chart.yaml
No-op version bump to re-trigger publishing of my previous change that had due to a bad GH token
> No-op Version Bump to re-trigger chart publishing

- .github/workflows/chart-releaser.yaml
Removing more refs to CR_TOKEN which seems to be no longer valid
> Removing More CR_TOKEN refs from chart publishing workflow

- .github/workflows/chart-releaser.yaml
- .github/workflows/releasedr.yaml
[Updating to use BROADBOT_TOKEN did not appear to work. ](https://github.com/broadinstitute/datarepo-helm/pull/230)
Looking at the [documentation](https://github.com/helm/chart-releaser-action#environment-variables) for helm/chart-releaser-action, it appears that using GITHUB_TOKEN instead should work. I also bumped to the latest version of the action because hopefully that should best reflect what the documentation suggests.
> DR-2885 - Chart Releaser Action: try new version and github token

- .github/workflows/chart-releaser.yaml
- .github/workflows/integrationChartBump.yaml
- .github/workflows/lint.yaml
- .github/workflows/releasedr.yaml
- .github/workflows/releasedrumbrella.yaml
- .github/workflows/releasenondr.yaml
- .github/workflows/terraAlphaChartBump.yaml
- .github/workflows/test.yaml
See https://github.com/DataBiosphere/jade-data-repo/pull/1404 PR description for more details about the changes.
Successful runs against this branch - I commented out the steps that actually do the real work so that I could test out the workflows. There is a small chance things break after uncommenting, but testing these workflows out of cycle can get us into a very wonky state that I'd like to avoid.
- Alpha Chart promotion ([case where notify-slack was set to false](https://github.com/broadinstitute/datarepo-helm/actions/runs/4120031778/jobs/7114351712))  ([case set to true](https://github.com/broadinstitute/datarepo-helm/actions/runs/4120047251))
- Chart releaser ([case where notify-slack was set to false](https://github.com/broadinstitute/datarepo-helm/actions/runs/4120056626)) …
> DR-2889: Upgrade Github actions due to Node 12 Deprecation 

- charts/oidc-proxy/Chart.yaml
- charts/oidc-proxy/templates/configmap.yaml
instead, just set `Access-Control-Allow-Origin: *` if the origin header is passed in
I left in the logic to do it conditionally though I'm not sure how useful it is
> DR-2932 Don't echo back the domain in allowed origin

- charts/oidc-proxy/Chart.yaml
- charts/oidc-proxy/templates/configmap.yaml
Note: per the docs, taking the safer method of not decoding the %2Fs but jst passing them through (which is actually what we want behavior-wise).  It's the API service's responsibility to understand what to do with the %2F characters.
The current behavior that this is replacing is to throw a 404 when a user passes in a %2F in the URL
> DR-3144 Allow encoded slashes (%2F) to be passed through by the apache proxy

- .github/workflows/integrationChartBump.yaml
- .github/workflows/lint.yaml
- .github/workflows/terraAlphaChartBump.yaml
- .github/workflows/test.yaml
https://broadworkbench.atlassian.net/browse/DR-2890
The save-state and set-output commands are going to be deprecated in Github Actions. This PR updates the syntax for set-output (save-state is not used anywhere). Here is more context about this change: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> [DR-2890] Update deprecated Github Actions set-output commands

- charts/datarepo-api/Chart.yaml
- charts/datarepo-api/templates/api-deployment.yaml
- charts/datarepo-api/values.yaml
This will allow us to configure reloader to restart TDR when its service account key is rotated.
I'm not sure the best way to test this under TDR's current setup. I rendered the chart locally with `helm template` and a values override and verified that the annotations are substituted in correctly:
```
kind: Deployment
metadata:
name: RELEASE-NAME-datarepo-api
labels: <...snip...>
annotations:
a: "2"
foo: bar
```
> [DDO-3199] Make it possible to pass in TDR deployment annotations in values files

- .github/workflows/releasedr.yaml
After https://github.com/broadinstitute/datarepo-helm/pull/247 was merged, the [datarepo-umbrella-release-action](https://github.com/broadinstitute/datarepo-umbrella-release-action/blob/99ab90f152de7ccc8c306ad751bac2719592ce76/action.yaml#L13) failed because it was still trying to include the `de-elasticsearch` chart. The new version of this action removes `de-elasticsearch` from the list of charts included in the umbrella chart.
> [DR-3413] Use new datarepo-umbrella-release-action

- charts/datarepo-api/templates/pod-running-policy.yaml
- charts/datarepo-api/templates/role.yaml
- charts/datarepo-api/templates/rolebinding.yaml
- charts/datarepo-api/values.yaml
The old rbac enabled flag wrapped both both pod security policy associated resources and also tdr's permission to talk to the k8s api. This separates them so that we can disable pod security policy without breaking tdrs ability to talk to k8s.
All bee creations are currently failing because of this.
> Attempting to Fix TDR in Bees following upgrade to GKE 1.25

- charts/datarepo-api/Chart.yaml
- charts/datarepo/Chart.yaml
I failed to bump chart versions correctly in https://github.com/broadinstitute/datarepo-helm/pull/249; this is a correction.
> [DDO-3475] Bump chart versions

- .github/workflows/integrationChartBump.yaml
- .github/workflows/releasedr.yaml
Bump to the latest version. 
This repo was not impacted by the issue described in DC-802, but it's still ideal to keep these versions up to date.
> DC-902: bump datarepo-actions

- .github/workflows/integrationChartBump.yaml
- .github/workflows/releasedr.yaml
https://broadworkbench.atlassian.net/browse/PROD-934
This reverts commit [2edd43f4bf7f7e673495a54b777950e7269480b6](https://github.com/broadinstitute/datarepo-helm/commit/2edd43f4bf7f7e673495a54b777950e7269480b6) from https://github.com/broadinstitute/datarepo-helm/pull/252
The commit was not strictly necessary to correct the issue at hand.  Following the merge, [API chart sync has been failing in all environments](https://github.com/broadinstitute/terra-github-workflows/actions/runs/8161732182), and we are attempting to triangulate the cause.
> [PROD-934] Revert "bump datarepo-actions (#252)"

- charts/gcloud-sqlproxy/Chart.yaml
- charts/gcloud-sqlproxy/templates/podrunningpolicy.yaml
- charts/gcloud-sqlproxy/templates/role.yaml
- charts/gcloud-sqlproxy/values.yaml
https://broadworkbench.atlassian.net/browse/PROD-934
This is a follow-on to https://github.com/broadinstitute/datarepo-helm/pull/249 which only made the necessary changes for TDR Bees to be compatible with GKE 1.25. TDR Bees don't use the `gcloud-sqlproxy`, and the existing `rbac.create` flag enabled more than just resources associated with PodSecurityPolicies, so I've added an additional `rbac.pspEnabled` flag to toggle only those resources without impacting other necessary operations (such as SA creation).
Defaulted this value to true to keep existing behavior the same.
- We will then disable it for each environment starting with Dev: https://github.com/broadinstitute/terra-helmfile/pull/5216
- … and likely cut it out altogether once everything is stable.
Bumped the `gcloud-sqlproxy` …
> [PROD-934] TDR gcloud-sqlproxy conditionally disables PodSecurityPolicies

- charts/oidc-proxy/Chart.yaml
- charts/oidc-proxy/templates/configmap.yaml
- charts/oidc-proxy/templates/oidc-proxy-deployment.yaml
- charts/oidc-proxy/values.yaml
https://broadworkbench.atlassian.net/browse/DR-3440
This change comes after several PROD incidents related to TDR's oidc-proxy, often requiring a manual refresh of the deployment to bring systems back in operation.  This upgrade matches what the rest of Terra uses, and is the latest available version.
PROD incidents:
- https://broadworkbench.atlassian.net/browse/PROD-926
- https://broadworkbench.atlassian.net/browse/PROD-934 (possibly related)
- https://broadworkbench.atlassian.net/browse/PROD-938
Per @rtitle - 'There were some significant changes between then: switch to RedHat UBI base image; concurrency bugfix in the mod_oauth2 module; remove stackdriver agent; and improved graceful shutdown.' 
This change was not quite a drop-in replacement, and required the following modifications:
1. …
> [DR-3440] Swap openidc-terra-proxy for httpd-terra-proxy v0.1.18

- charts/create-secret-manager-secret/Chart.yaml
- charts/create-secret-manager-secret/values.yaml
This is the 3rd of 5 PRs to migrate data repo to ESO from Vault. This PR is an intermediate between adding ESO secrets ([1](https://github.com/broadinstitute/datarepo-helm/pull/253) [2](https://github.com/broadinstitute/terra-helmfile/pull/5213)) and cutover to ESO ([4](https://github.com/broadinstitute/terra-helmfile/pull/5296) [5](https://github.com/broadinstitute/datarepo-helm/pull/261)). This repo (datarepo-helm) will hold the create-secret-manager-secret chart while terra-helmfile will hold the values.
This PR sets `secrets` (list of vault secrets) to `[]`. This is in preparation for when we deleted the Vault values from terra-helmfile (PR 4) but before the Vault secret parsing is removed from the datarepo-helm chart (PR 5).
This PR was tested by using [the datarepo-helm-definitions …
> DDO-3517: Set empty list for vault secrets

- charts/datarepo-api/Chart.yaml
- charts/datarepo-api/templates/service-monitor.yaml
- charts/datarepo-api/values.yaml
This adds support for creation of the [`ServiceMonitor`](https://prometheus-operator.dev/docs/operator/design/#servicemonitor) kubernetes resource extension that can be used by prometheus to automatically discover and pull metrics from a targeted set of k8s pods.
The advantage of this approach is that it automatically tags all timeseries collected via this method with relevant k8s metadata such as namespace, which deployment/container it is etc...
This is the same method used by the rest of Terra for collecting these metrics. It is a replacement for [this approach](https://github.com/broadinstitute/datarepo-helm-definitions/blob/d3a2b0ae1f78468f425a0889c9b6b7a9c3f1a469/dev/monitoring/kube-prometheus-stack.yaml#L18) in the TDR prometheus which achieves a similar goal scraping the metric …
> DDO-3415 Add support for Prometheus ServiceMonitor Resource to datarepo-api

- .github/workflows/lint.yaml
https://broadworkbench.atlassian.net/browse/DCJ-31
The Helm Chart Linter runs only on commits to PRs. Slack notifications on the outcome are unnecessary and noisy. If the action fails, the PR cannot be merged.
Current state of [#jade-spam](https://broadinstitute.slack.com/archives/CK9M0ENRJ/p1713300313079569) (which Data Custodian Journeys team is in the process of auditing and consolidating):
Confirming that when this PR's lint run ran and succeeded, no notification was emitted to #jade-spam.
> [DCJ-31] Remove Slack notifications from PR lint action

- .github/workflows/chart-releaser.yaml
- .github/workflows/integrationChartBump.yaml
- .github/workflows/releasedr.yaml
- .github/workflows/releasedrumbrella.yaml
https://broadworkbench.atlassian.net/browse/DCJ-28
More thorough background: https://github.com/DataBiosphere/jade-data-repo/pull/1654
I set up a new Github repository variable `SLACK_NOTIFICATION_CHANNELS`:
And made the following changes to existing Slack notifications:
- `chart-releaser`, `integrationChartBump`: removed Slack notifications as these are called within `releasedrumbrella`.
- `releasedr`, `releasedrumbrella`: reworked Slack notifications to be emitted by Sherlock on failures or retries to our variable-driven channel list.
- I think we should have the insight we need into deployments from Beehive's Slack deploy hooks, but I am not confident enough to fully remove them.  If / when these fail, we can take a closer look at the full suite of notifications that go out and pare …
> [DCJ-28] Slack DCJ team on release failures, retries

- charts/datarepo/Chart.yaml
bumps postgres chart from 0.26.0 to 0.40.0, only affects bees
> bump to v40

- charts/datarepo-api/Chart.yaml
- charts/datarepo-api/values.yaml
__Jira ticket__: https://broadworkbench.atlassian.net/browse/DCJ-470
Since the beginning of 2024, TDR Prod backend pods have triggered high memory alerts (>95% of limit) over 50 times.  We'd like to increase the memory limits on our backend pods for increased system reliability and decreased alerting noise.
This PR partially fulfills the ticket above.  We must roll out PRs in the following order:
1. This PR
2. https://github.com/DataBiosphere/jade-data-repo/pull/1727 (because the Docker memory limit should be less than the pod memory limit)
Increase `datarepo-api` pod memory limit, and convert memory configuration values from Mi to Gi for easier readability, following precedent set by other services in `terra-helmfile`.
- `resources.limits.memory` increased from 2.5Gi -> 4.5Gi
- …
> [DCJ-470] Increase datarepo-api pod memory limit

- charts/datarepo-api/Chart.yaml
https://broadworkbench.atlassian.net/browse/DCJ-470
First thing this morning, I merged this jade-data-repo PR: https://github.com/DataBiosphere/jade-data-repo/pull/1726
Which triggered an api chart bump to 0.0.701: https://github.com/DataBiosphere/jade-data-repo/commit/1f1fb412cfb1236e03fed49fd0a80957a50cf66c
Later, I merged this datarepo-helm PR, where I had previously manually bumped the datarepo-api chart version to 0.0.701: https://github.com/broadinstitute/datarepo-helm/pull/272
That was my oversight: while that chart bump was correct at the time, it was no longer a bump when I merged and matched the version already present.  Hence, the empty commit failures which prevented integration test charts from being promoted: https://github.com/broadinstitute/datarepo-helm/actions/runs/978128 …
> [DCJ-470] Bump datarepo-api chart version to 0.0.702

- .github/workflows/integrationChartBump.yaml
- .github/workflows/releasedr.yaml
Partially addresses https://broadworkbench.atlassian.net/browse/DCJ-476
Update the specified versions of the merger action call as updated in https://github.com/broadinstitute/datarepo-actions/pull/85
> DCJ-476: Specify the latest merger action version

- .github/workflows/integrationChartBump.yaml
https://broadworkbench.atlassian.net/browse/DCJ-616
In TDR, Changes were recently made to the action which runs on PRs:
- https://github.com/DataBiosphere/jade-data-repo/pull/1781 
- https://github.com/DataBiosphere/jade-data-repo/pull/1794
This workflow tries to (unsuccessfully) modify the action, breaking it in the process:
https://github.com/DataBiosphere/jade-data-repo/commit/31b4714b0032fcc4c982e64709c68ce45e576fa6
Links to failed builds:
https://github.com/DataBiosphere/jade-data-repo/actions/runs/10708679629
https://github.com/DataBiosphere/jade-data-repo/actions/runs/10708678706
https://github.com/DataBiosphere/jade-data-repo/actions/runs/10708668823
> [DCJ-616] Do not update action anymore
