broadinstitute/datarepo-helm

charts/gcloud-sqlproxy/Chart.yaml, charts/gcloud-sqlproxy/templates/deployment.yaml, charts/gcloud-sqlproxy/templates/svc.yaml
If you choose a long name, you can get unlucky and end up with a port that ends in `-`. k8s complains.
=> Trim - from port suffix to avoid errors.

README.md
=> first pass at updated readme

charts/datarepo-api/Chart.yaml, charts/datarepo-api/templates/k8s-access-role.yaml
Adding permissions so datarepo-api can list the deployments and get its deployment id.
=> Add deployment permissions; bump api chart version

charts/datarepo-ui/Chart.yaml, charts/datarepo-ui/templates/configmap.yaml, charts/datarepo-ui/templates/pod-running-policy.yaml, charts/datarepo-ui/templates/ui-deployment.yaml, charts/datarepo-ui/values.yaml
Switch the container, readiness probe, and liveness probe ports to 8080 to match non-root nginx container.
=> Switch ui chart ports to 8080

charts/datarepo-api/Chart.yaml, charts/datarepo-api/templates/api-deployment.yaml
CAUTION: Do not update chart version until Data-repo PR merged. 
https://github.com/DataBiosphere/jade-data-repo/pull/670
=> DR-1416: Switch api liveness and readiness endpoints to spring boot actuator endpoints

charts/datarepo-api/Chart.yaml, charts/datarepo-api/values.yaml, charts/datarepo-ui/Chart.yaml, charts/datarepo-ui/templates/ui-deployment.yaml, charts/oidc-proxy/Chart.yaml, charts/oidc-proxy/templates/oidc-proxy-deployment.yaml
=> DR-1550 Call /status less frequently and set memory/cpu configs for api deployment

charts/oidc-proxy/Chart.yaml, charts/oidc-proxy/templates/oidc-frontend-config.yaml, charts/oidc-proxy/templates/oidc-ingress.yaml, charts/oidc-proxy/values.yaml
=> added front end config to oidc for redirect http to https and ssl cert policy to LB

charts/datarepo-ui/Chart.yaml, charts/datarepo-ui/values.yaml
Update versions in **0.3.0**.
*Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/DataBiosphere/jade-data-repo-ui/actions/runs/562293107).*
=> Datarepo version update: 0.3.0

charts/datarepo-api/Chart.yaml, charts/datarepo-api/values.yaml
Update versions in **1.18.0**.
*Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/DataBiosphere/jade-data-repo/actions/runs/573592831).*
=> Datarepo version update: 1.18.0

charts/datarepo/Chart.lock, charts/datarepo/Chart.yaml
*Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/broadinstitute/datarepo-helm/actions/runs/575357244).*
=> Datarepo umbrella version update

charts/datarepo-ui/Chart.yaml, charts/datarepo-ui/values.yaml
Update versions in **0.4.0**.
*Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/DataBiosphere/jade-data-repo-ui/actions/runs/582354349).*
=> Datarepo version update: 0.4.0

charts/datarepo-ui/Chart.yaml, charts/datarepo-ui/values.yaml
Update versions in **0.5.0**.
*Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/DataBiosphere/jade-data-repo-ui/actions/runs/582495811).*
=> Datarepo version update: 0.5.0

charts/datarepo-ui/Chart.yaml, charts/datarepo-ui/values.yaml
Update versions in **0.6.0**.
*Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/DataBiosphere/jade-data-repo-ui/actions/runs/582596629).*
=> Datarepo version update: 0.6.0

charts/datarepo-ui/Chart.yaml, charts/datarepo-ui/values.yaml
Update versions in **0.7.0**.
*Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/DataBiosphere/jade-data-repo-ui/actions/runs/582627148).*
=> Datarepo version update: 0.7.0

charts/datarepo-ui/Chart.yaml, charts/datarepo-ui/values.yaml
Update versions in **0.8.0**.
*Note: This PR was opened by the [update-env GitHub Actions workflow](https://github.com/DataBiosphere/jade-data-repo-ui/actions/runs/582743638).*
=> Datarepo version update: 0.8.0

.github/workflows/integrationChartBump.yaml, .github/workflows/releasedr.yaml, .github/workflows/terraAlphaChartBump.yaml
https://github.com/broadinstitute/datarepo-actions/pull/46 should be merged first
=> DR-1510: Add git pull to merge

charts/datarepo-ui/Chart.yaml, charts/datarepo-ui/templates/configmap.yaml
=> Revert DR-1651 - CORS policy too strict

charts/datarepo-ui/Chart.yaml, charts/datarepo-ui/templates/configmap.yaml
Adding additional domains to the CSP headers that should fix the problems we saw in dev. I'll be deploying this to my personal branch and testing before merging.
=> DR-1651 CSP Headers Remediation

charts/datarepo-ui/Chart.yaml
I gotta stop forgetting to do this...
=> Bump UI chart version

charts/datarepo-ui/Chart.yaml
=> DR-1665 Bump Chart Versions

charts/datarepo-api/Chart.yaml
...to try to be able to re-run the chart deploy
=> DR-1822 Bump the chart version

.github/workflows/chart-releaser.yaml, .github/workflows/releasedr.yaml
Maybe this will at least log something more meaningful?
=> DR-1822 Bump the chart releaser version

.github/workflows/chart-releaser.yaml, .github/workflows/releasedr.yaml
Hoping this will allow to fail silently
=> DR-1822: Try to skip existing versions on upload

.github/workflows/releasedr.yaml, charts/oidc-proxy/Chart.yaml, charts/oidc-proxy/templates/configmap.yaml
...also a drive by action step name typo fix
=> DR-1666 Add Strict-Transport-Security header to all responses

charts/oidc-proxy/Chart.yaml, charts/oidc-proxy/templates/configmap.yaml
Spaces are no good in headers apparently.  Tested and this fixes it
=> DR-1666 Fix new header definition

charts/datarepo-api/Chart.yaml, charts/datarepo-api/templates/api-deployment.yaml
These are used by the stairway version 0.0.66 (updated here): https://github.com/DataBiosphere/jade-data-repo/pull/1109/files
=> [DR-2163] Add new kubernetes environment variables

charts/datarepomonitoring/Chart.lock, charts/datarepomonitoring/Chart.yaml, charts/datarepomonitoring/values.yaml
this way it will work with the terra helmfile
=> DR-2291 Add a boolean to enable the front end config

.github/workflows/chart-releaser.yaml
Thinking maybe we need to explicitly add the prometheus repo
=> DR-2291 See if this fixes the chart releaser

charts/datarepo-api/templates/api-deployment.yaml
Adding some more terra common lib properties as a result of our common lib upgrade
=> DR-2298 Add common lib properties to api deployment

charts/de-elasticsearch/Chart.yaml
Follow-up to bump chart version.
=> DC-97: Bump elasticsearch chart version

charts/oidc-proxy/Chart.yaml, charts/oidc-proxy/templates/configmap.yaml
(same fix as broad Terra: https://github.com/broadinstitute/firecloud-develop/pull/2789)
=> DR-2443 Disable proxy cache encryption

.github/workflows/test.yaml, charts/datarepo-ui/Chart.yaml, charts/datarepo-ui/templates/configmap.yaml
Make sure that the ui proxy doesn't block the swagger yaml file in the API service
=> DR-1784 Allow accessing the swagger definition through the UI proxy

charts/oidc-proxy/Chart.yaml
...whoops.  Missed as part of PR #198.  Going to merge as part of that PR review
=> DR-2457 Bump chart

charts/datarepo-ui/Chart.yaml
=> DDO-1674 Forgot to Bump UI chart version

.github/workflows/chart-releaser.yaml, .github/workflows/lint.yaml, .github/workflows/releasedr.yaml, .github/workflows/test.yaml
Update all helm repo add commands to include terra-helm
=> DDO-1674 Part 3 Fix Helm repo list

charts/install-secrets-manager/templates/role.yaml
Verified by https://ap-argocd.dsp-devops.broadinstitute.org/applications/install-secrets-manager-dsp-ci?resource=&conditions=false&operation=false
=> [DDO-2129] Fix secrets-manager for k8s 1.22

charts/install-secrets-manager/Chart.yaml
Thelma is so good I forgot how to do a normal chart release
=> [DDO-2129] Actually release the new secrets-manager chart

charts/datarepo-api/Chart.yaml, charts/datarepo-ui/Chart.yaml, charts/oidc-proxy/Chart.yaml
Bump the charts I missed in:
https://github.com/broadinstitute/datarepo-helm/pull/217
=> DDO-2153 Chart bump

charts/gcloud-sqlproxy/Chart.yaml, charts/gcloud-sqlproxy/templates/role.yaml, charts/gcloud-sqlproxy/templates/rolebinding.yaml, charts/oidc-proxy/Chart.yaml, charts/oidc-proxy/templates/oidc-ingress.yaml
Like it says on the tin.  There'll be a followon in datarepo-helm-defintions to use the new charts
=> DR-2698 Remove deprecated APIs from our ingress and sql proxy

charts/datarepo-ui/Chart.yaml, charts/datarepo-ui/templates/configmap.yaml
This should eliminate the following issue:
=> DR-2735 Make sure to allow fontawesome fonts in the UI

.github/workflows/integrationChartBump.yaml, .github/workflows/releasedr.yaml, .github/workflows/terraAlphaChartBump.yaml
See PR & description for change info! https://github.com/broadinstitute/datarepo-actions/pull/76
Thank you @choover-broad!!
=> DR-2871: Bump datarepo-actions version

charts/install-secrets-manager/Chart.yaml
There was still an issue with the chart publishing workflow, trying again
=> DDO-2562 Yet More Secrets Manager Version Bumping

.github/workflows/releasedr.yaml, .github/workflows/releasedrumbrella.yaml
...instead of the CR_TOKEN secret
=> DR-2885 Use the BROADBOT_TOKEN secret for chart releasing

.github/workflows/releasedrumbrella.yaml, .github/workflows/releasenondr.yaml
See description here: https://github.com/DataBiosphere/jade-data-repo/pull/1408
=> DR-2889 - update slack job status

.github/workflows/releasedrumbrella.yaml
https://broadinstitute.slack.com/archives/CD4HBRFMG/p1697811755411519?thread_ts=1697744338.733419&cid=CD4HBRFMG @snf2ye with a great catch
=> [DDO-3249] Remove errant alpha reference

.github/workflows/integrationChartBump.yaml, .github/workflows/releasedr.yaml
https://github.com/broadinstitute/datarepo-actions/pull/83
https://github.com/broadinstitute/datarepo-actions/pull/84
=> DC-904, DC-923: bump datarepo-actions version

.github/workflows/integrationChartBump.yaml
Fix from this PR:
https://github.com/broadinstitute/datarepo-helm/pull/262
Relates to:
https://github.com/DataBiosphere/jade-data-repo/pull/1641
https://github.com/DataBiosphere/jade-data-repo-ui/pull/1639
=> DDO-3599: Update version name in GHA

charts/datarepo-api/Chart.yaml, charts/datarepo-api/templates/service-monitor.yaml
Unfortunately there isn't really good way to test these prior to merge because of the separate helm repo. I had a typo in #265. This fixes it
=> DDO-3415 Fix Typo In ServiceMonitor Template

charts/datarepo/Chart.lock, charts/datarepo/Chart.yaml
=> bump chart

charts/datarepo-ui/templates/configmap.yaml, charts/oidc-proxy/templates/configmap.yaml, charts/oidc-proxy/templates/oidc-proxy-deployment.yaml, charts/oidc-proxy/values.yaml
https://broadworkbench.atlassian.net/browse/WOR-1646
=> WOR-1646 remove tcell

charts/datarepo-api/README.md, charts/datarepo-api/templates/_helpers.tpl, charts/datarepo-api/templates/api-deployment.yaml, charts/datarepo-api/templates/secrets.yaml, charts/datarepo-api/values.yaml
Jira Ticket: 
https://broadworkbench.atlassian.net/browse/DT-916
Summary: 
Remove references to RBS service account. This will hopefully fix the error on dev: https://broadinstitute.slack.com/archives/C07U5CFUXV0/p1731947382807979
=> [DT-916]Enable directly accessing RBS with TDR SA (part 2)

.github/workflows/lint.yaml
https://broadworkbench.atlassian.net/browse/DT-1122
- Do not persist credentials if not needed
=> [DT-1122] Apply `zizmor` suggestions

charts/datarepo-api/templates/api-deployment.yaml
revert: disable liquibase analytics
I accidentally commited to master while working on this ticket:https://broadworkbench.atlassian.net/browse/DT-990
I want to revert these changes, then put them up for review.
=> revert: disable liquibase analytics
